Baseline/Models/InlineEditors/ColorPickerEditor/ColorPickerEditorViewModel.cs
namespace Models.InlineEditors
{
    /// <summary>
    /// View model for Color picker editor.
    /// </summary>
    public sealed class ColorPickerEditorViewModel : InlineEditorViewModel
    {
        /// <summary>
        /// Color CSS class.
        /// </summary>
        public string ColorCssClass { get; set; }
    }
}

Baseline/Models/InlineEditors/ImageUploaderEditor/ImageUploaderEditorViewModel.cs
using CMS.DocumentEngine;

namespace Models.InlineEditors
{
    /// <summary>
    /// View model for Image uploader editor.
    /// </summary>
    public class ImageUploaderEditorViewModel : InlineEditorViewModel
    {
        /// <summary>
        /// Image.
        /// </summary>
        public DocumentAttachment Image { get; set; }


        /// <summary>
        /// Indicates if the message should be positioned absolutely for empty image.
        /// </summary>
        public bool UseAbsolutePosition { get; set; }


        /// <summary>
        /// Position of the message in case of absolute position.
        /// </summary>
        public PanelPositionEnum MessagePosition { get; set; } = PanelPositionEnum.Center;
    }
}

Baseline/Models/InlineEditors/ImageUploaderEditor/PanelPositionEnum.cs
namespace Models.InlineEditors
{
    /// <summary>
    /// Position of the informational panel for image uploader editor.
    /// </summary>
    public enum PanelPositionEnum
    {
        /// <summary>
        /// Aligned to the top of the widget content.
        /// </summary>
        Top,


        /// <summary>
        /// Aligned to the center of the widget content.
        /// </summary>
        Center,


        /// <summary>
        /// Aligned to the bottom of the widget content.
        /// </summary>
        Bottom
    }
}

Baseline/Models/InlineEditors/InlineEditorViewModel.cs
namespace Models.InlineEditors
{
    /// <summary>
    /// Base class for inline editor view models.
    /// </summary>
    public abstract class InlineEditorViewModel
    {
        /// <summary>
        /// Name of the widget property to edit.
        /// </summary>
        public string PropertyName { get; set; }
    }
}

Baseline/Models/InlineEditors/SpinnerEditor/SpinnerEditorViewModel.cs
namespace Models.InlineEditors
{
    /// <summary>
    /// View model for Spinner editor.
    /// </summary>
    public sealed class SpinnerEditorViewModel : InlineEditorViewModel
    {
        /// <summary>
        /// Number of items to show.
        /// </summary>
        public int Count { get; set; }
    }
}

Baseline/Controllers/InlineEditors/ImageUploaderController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.IO;
using CMS.Membership;
using CMS.SiteProvider;

using Kentico.PageBuilder.Web.Mvc;
using Kentico.Web.Mvc;

namespace Controllers.Widgets
{
    public class ImageUploaderController : Controller
    {
        private static readonly HashSet<string> allowedExtensions = new HashSet<string>(new[]
        {
            ".bmp",
            ".gif",
            ".ico",
            ".png",
            ".wmf",
            ".jpg",
            ".jpeg",
            ".tiff",
            ".tif"
        }, StringComparer.OrdinalIgnoreCase);


        [HttpPost]
        public JsonResult Upload(int pageId)
        {
            if (!HttpContext.Kentico().PageBuilder().EditMode)
            {
                throw new HttpException(403, "It is allowed to upload an image only when the page builder is in the edit mode.");
            }

            var page = DocumentHelper.GetDocument(pageId, null);
            if (!CheckPagePermissions(page))
            {
                throw new HttpException(403, "You are not authorized to upload an image to the page.");
            }

            var imageGuid = Guid.Empty;

            foreach (string requestFileName in Request.Files)
            {
                imageGuid = AddUnsortedAttachment(page, requestFileName);
            }

            return Json(new { guid = imageGuid });
        }


        private Guid AddUnsortedAttachment(TreeNode page, string requestFileName)
        {
            if (!(Request.Files[requestFileName] is HttpPostedFileWrapper file))
            {
                return Guid.Empty;
            }

            var directoryPath = EnsureUploadDirectory();
            var imagePath = GetTempFilePath(directoryPath, file);

            byte[] data = new byte[file.ContentLength];
            file.InputStream.Seek(0, System.IO.SeekOrigin.Begin);
            file.InputStream.Read(data, 0, file.ContentLength);

            CMS.IO.File.WriteAllBytes(imagePath, data);

            var attachmentGuid = DocumentHelper.AddUnsortedAttachment(page, Guid.Empty, imagePath).AttachmentGUID;

            CMS.IO.File.Delete(imagePath);

            return attachmentGuid;
        }


        private string GetTempFilePath(string directoryPath, HttpPostedFileBase file)
        {
            var fileName = Path.GetFileName(file.FileName);
            if (string.IsNullOrEmpty(fileName))
            {
                throw new InvalidOperationException("Cannot upload file without file name.");
            }

            if (!allowedExtensions.Contains(Path.GetExtension(file.FileName)))
            {
                throw new InvalidOperationException("Cannot upload file of this type.");
            }

            return Path.Combine(directoryPath, fileName);
        }


        private string EnsureUploadDirectory()
        {
            var directoryPath = $"{Server.MapPath(@"~\")}App_Data\\Temp\\ImageUploader";

            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            return directoryPath;
        }


        private bool CheckPagePermissions(TreeNode page)
        {
            return page?.CheckPermissions(PermissionsEnum.Modify, SiteContext.CurrentSiteName, MembershipContext.AuthenticatedUser) ?? false;
        }
    }
}

Baseline/Views/Shared/InlineEditors/_ColorPickerEditor.cshtml
@model Models.InlineEditors.ColorPickerEditorViewModel

@using (Html.Kentico().BeginInlineEditor("color-picker-editor", Model.PropertyName, new { @class = "color-picker-editor" }))
{
    <div class="inline-editor-btn-group">
        <ul class="inline-editor-btn-group-actions">
            <li>
                <button id="first-color-btn" type="button">
                    <i class="color-btn first-color"></i>
                </button>
            </li>
            <li>
                <button id="second-color-btn" type="button">
                    <i class="color-btn second-color"></i>
                </button>
            </li>
            <li>
                <button id="third-color-btn" type="button">
                    <i class="color-btn third-color"></i>
                </button>
            </li>
        </ul>
    </div>
}

Baseline/Views/Shared/InlineEditors/_ImageUploaderEditor.cshtml
@using Models.InlineEditors
@model Models.InlineEditors.ImageUploaderEditorViewModel

@{
    HtmlString GetActionUrl()
    {
        return Url.Kentico().AuthenticateUrl(Url.Action("Upload", "ImageUploader", new
        {
            pageId = Context.Kentico().PageBuilder().PageIdentifier
        }), false);
    }

    string GetContainerClass()
    {
        if (Model.Image != null)
        {
            return "uploader-container";
        }

        return Model.UseAbsolutePosition ? "uploader-empty-container absolute" : "uploader-empty-container";
    }

    string GetMessagePositionClass()
    {
        switch (Model.MessagePosition)
        {
            case PanelPositionEnum.Bottom:
                return "bottom";

            case PanelPositionEnum.Top:
                return "top";

            default:
                return "center";
        }
    }
}
@using (Html.Kentico().BeginInlineEditor("image-uploader-editor", Model.PropertyName,
    new
    {
        @class = "image-uploader-editor",
        data_url = GetActionUrl().ToString()
    }))
{
    <div class="@GetContainerClass()">
        <div class="uploader">
            <div class="dz-message @GetMessagePositionClass()">
                <i class="icon-arrow-up-line"></i>
                <div>
                    @Html.GetUIString("InlineEditors.ImageUploader.DropText")
                </div>
            </div>
        </div>
    </div>
}

Baseline/Views/Shared/InlineEditors/_SpinnerEditor.cshtml
@model Models.InlineEditors.SpinnerEditorViewModel

@using (Html.Kentico().BeginInlineEditor("spinner-editor", Model.PropertyName, new { @class = "spinner-editor" }))
{
    <div class="inline-editor-btn-group">
        <ul class="inline-editor-btn-group-actions">
            <li><button id="minus-btn" type="button" title="@Html.GetUIString("InlineEditors.SpinnerEditor.Minus")"><b>-</b></button></li>
            <li><button id="value-btn" type="button" disabled><b id="value-placeholder">@Model.Count</b></button></li>
            <li><button id="plus-btn" type="button" title="@Html.GetUIString("InlineEditors.SpinnerEditor.Plus")"><b>+</b></button></li>
        </ul>
    </div>
}